name: publish to nuget
on:
  push:
    branches:
      - master
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies
        run: dotnet restore TealInc.PostHogClient.sln
      - name: Build solution
        run: dotnet build TealInc.PostHogClient.sln --no-restore --configuration Release
      - name: Pack solution
        run: dotnet pack TealInc.PostHogClient.sln --no-build --configuration Release --include-symbols -p:SymbolPackageFormat=snupkg -o .
      - name: Publish packages to NuGet
        run: dotnet nuget push *.nupkg --api-key ${{secrets.NUGET_PUBLISH_KEY}} --source "https://api.nuget.org/v3/index.json" --skip-duplicate